"""Validate a signed Beat This release before changing API canonical records."""
from __future__ import annotations

import argparse
import base64
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

import promote_modal
import release_modal


def verify_signature(record: dict, signature: str, public_key: str) -> None:
    try:
        signature_bytes = base64.b64decode(signature, validate=True)
    except ValueError as exc:
        raise ValueError("promotion signature is not base64") from exc
    if len(signature_bytes) != 64:
        raise ValueError("promotion signature is not Ed25519")
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        payload_path = root / "record.json"
        signature_path = root / "signature.bin"
        public_key_path = root / "public.pem"
        payload_path.write_text(promote_modal.canonical(record))
        signature_path.write_bytes(signature_bytes)
        public_key_path.write_text(public_key)
        result = subprocess.run(
            [
                "openssl", "pkeyutl", "-verify", "-pubin",
                "-inkey", str(public_key_path), "-rawin",
                "-in", str(payload_path), "-sigfile", str(signature_path),
            ],
            capture_output=True,
            check=False,
        )
    if result.returncode:
        raise ValueError("promotion signature does not match the public key")


def validate(
    bundle: object,
    public_key: str,
    evidence: dict,
    refresh: object,
    health: object,
) -> dict:
    release_modal.validate_release_evidence(evidence)
    if (
        not isinstance(refresh, dict)
        or refresh.get("schemaVersion") != 1
        or refresh.get("provider") != "BEAT_THIS"
        or refresh.get("modalAppId") != evidence["modalAppId"]
        or refresh.get("modalDeploymentId") != evidence["modalDeploymentId"]
        or not isinstance(refresh.get("stoppedContainerIds"), list)
        or refresh.get("staleContainerIds") != []
    ):
        raise ValueError("container refresh proof does not match release evidence")
    if not isinstance(bundle, dict) or set(bundle) != {"record", "signature"}:
        raise ValueError("promotion bundle must contain exactly record and signature")
    record = bundle.get("record")
    signature = bundle.get("signature")
    if not isinstance(record, dict) or not isinstance(signature, str):
        raise ValueError("promotion bundle fields are invalid")
    expected_fields = {
        "provider": "BEAT_THIS",
        "modalAppId": evidence["modalAppId"],
        "modalDeploymentId": evidence["modalDeploymentId"],
        "modalFunctionId": evidence["modalFunctionId"],
        "modalImageId": evidence["modalImageId"],
        "endpointOrigin": evidence["endpointOrigin"],
        "sourceRevision": evidence["sourceRevision"],
        "sourceImageDigest": evidence["sourceImageDigest"],
        "releaseEvidenceSha256": promote_modal.release_evidence_sha256(evidence),
    }
    if any(record.get(key) != value for key, value in expected_fields.items()):
        raise ValueError("promotion record does not match captured release evidence")
    smoke_checkpoint = evidence["smokeEvidence"]["checkpoint"]["sha256"]
    if record.get("checkpointSha256") != smoke_checkpoint:
        raise ValueError("promotion checkpoint does not match real smoke evidence")
    promote_modal.verify_live_health(health, record)
    verify_signature(record, signature, public_key)
    return record


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as temporary:
        temporary.write(text)
        temporary.flush()
        os.fsync(temporary.fileno())
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)


def activate(
    bundle: dict,
    public_key: str,
    evidence: dict,
    refresh: dict,
    health: dict,
    api_output: Path,
    release_output: Path,
) -> None:
    record = validate(bundle, public_key, evidence, refresh, health)
    bundle_json = promote_modal.canonical(bundle)
    generated = (
        "/* Generated by the fail-closed Beat This release workflow. */\n"
        f"export const committedBeatThisPromotionBundle = {json.dumps(bundle_json)};\n"
        f"export const committedBeatThisPromotionPublicKey = {json.dumps(public_key)};\n"
    )
    release = {
        "schemaVersion": 1,
        "provider": "BEAT_THIS",
        "record": record,
        "signature": bundle["signature"],
        "publicKey": public_key,
        "containerRefresh": refresh,
        "smokeEvidence": evidence["smokeEvidence"],
        "liveHealth": health,
    }
    # Validate both complete documents before replacing either canonical file.
    if not re.fullmatch(r"[a-f0-9]{40}", record["sourceRevision"]):
        raise ValueError("release source revision is not immutable")
    release_json = promote_modal.canonical(release) + "\n"
    atomic_write(api_output, generated)
    atomic_write(release_output, release_json)


def main() -> None:
    parser = argparse.ArgumentParser()
    for name in (
        "bundle", "public-key", "evidence", "refresh", "health", "api-output",
        "release-output",
    ):
        parser.add_argument(f"--{name}", required=True)
    args = parser.parse_args()
    activate(
        json.loads(Path(args.bundle).read_text()),
        Path(args.public_key).read_text(),
        json.loads(Path(args.evidence).read_text()),
        json.loads(Path(args.refresh).read_text()),
        json.loads(Path(args.health).read_text()),
        Path(args.api_output),
        Path(args.release_output),
    )


if __name__ == "__main__":
    main()